Repository elastic/opbeans-java, pull requests merged in 2019-11, with the labels that each got.

#38 lighter docker image for the obpeans-java
  .dockerignore
  Dockerfile
Labels: automation

#41 Add chained exception
  opbeans/src/main/java/co/elastic/apm/opbeans/controllers/IndexController.java
  opbeans/src/main/resources/logback.xml
Labels: [zube]: In Review

#42 [jjbb] check_paths_for_matches.py not required anymore
  .ci/bin/check_paths_for_matches.py
Labels: automation, ci

#43 ci(jenkins): Update Jenkins badge
  README.md
Labels: automation, ci

#44 feat: enable log correlation on docker compose files
  docker-compose-elastic-cloud.yml
  docker-compose.yml
Labels: automation, enhancement

#33 feat: enable opbeans java release process
  .ci/bump-version.sh
  .gitignore
  Makefile
Labels: [zube]: In Review, automation
